### PR TITLE
fix: prevent panic and improve logging

### PR DESCRIPTION
**Pull request by logicfox**
Thanks for this great little tool. Exactly what I was looking for. However, I found a few issues which I fixed to get it working.

### CODE REVIEW

**Comment by wenzel-felix** [comment]
Hi @logicfox, thanks for your contribution. I'll have a look at your changes. From what I see on first glance, I would just ask you if you want to create this new dockerfile to not overwrite the current one but instead add a Dockerfile.local.
Cheers

**Comment by logicfox** [comment]
Restored the old Dockerfile and renamed the new one as requested.

**Comment by logicfox** [comment]
@wenzel-felix have you had a chance to review this PR? I'm currently using my own fork and would love to switch to your upstream repo.

**Comment by wenzel-felix** [comment]
Hi @logicfox , sorry for the late reply. I'll review, test and merge today.

**Comment by wenzel-felix** [comment]
Thank you for your contribution.

**Pull request merged**
